export const translations: Record<string, Record<string, string>> = {
  EN: {
    account: "Account",
    balance: "Balance",
    earned: "Earned",
    tasks: "Tasks",
    referralSystem: "REFERRAL SYSTEM",
    members: "Members",
    promoText: "Earn 10% Instant Cash every time your friends upgrade their VIP tier!",
    referredMembers: "REFERRED MEMBERS",
    noReferrals: "No referrals yet. Start growing your network!",
    invitedBy: "Invited by",
    resources: "RESOURCES",
    adminPanel: "Admin Control Panel",
    vipUpgrade: "VIP Upgrade",
    txHistory: "Transaction History",
    securityPass: "Security & Password",
    supportCenter: "Support Center",
    aboutUs: "About Us",
    languageBtn: "LANGUAGE / لغة",
    selectLanguage: "Select Language / اختر اللغة",
    identityTitle: "Personal Identity Info",
    identitySubtitle: "Update your account username and upload a fresh profile image avatar",
    accountUsername: "ACCOUNT USERNAME",
    cancel: "Cancel",
    secureChanges: "Secure Changes"
  },
  AR: {
    account: "الحساب الشخصي",
    balance: "الرصيد الحالي",
    earned: "إجمالي الأرباح",
    tasks: "المهام اليومية",
    referralSystem: "نظام الإحالة والشبكة",
    members: "أعضاء",
    promoText: "احصل على عمولة فورية بنسبة 10% في كل مرة يقوم فيها أصدقاؤك بترقية حساباتهم!",
    referredMembers: "الأعضاء المسجلين بواسطتك",
    noReferrals: "لا يوجد إحالات بعد. ابدأ في بناء شبكتك الآن!",
    invitedBy: "تمت دعوتك بواسطة",
    resources: "غرفة التحكم والموارد",
    adminPanel: "لوحة تحكم الإدارة العليا",
    vipUpgrade: "ترقية رتبة VIP",
    txHistory: "سجل المعاملات المالي",
    securityPass: "الأمان وكلمات السر",
    supportCenter: "مركز الدعم الفني 24/7",
    aboutUs: "حول المنصة",
    languageBtn: "اللغة / LANGUAGE",
    selectLanguage: "اختر لغتك المفضلة",
    identityTitle: "بيانات الهوية الشخصية",
    identitySubtitle: "قم بتحديث اسم المستخدم الخاص بك وتغيير صورة البروفايل الحية",
    accountUsername: "اسم المستخدم الخاص بالحساب",
    cancel: "إلغاء",
    secureChanges: "حفظ وتأمين التعديلات"
  }
};